# Generated by Django 2.2.5 on 2021-04-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210420_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cityy',
            field=models.CharField(default=False, max_length=80),
        ),
    ]
