# Generated by Django 2.2.5 on 2021-04-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_cityy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cityy',
        ),
    ]
